# Generated by Django 5.0.6 on 2024-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0019_alter_userrank_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_ranks',
            field=models.ManyToManyField(related_name='users', to='v3.userrank'),
        ),
    ]
