# Generated by Django 5.0.6 on 2024-10-03 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0020_usermodel_user_ranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='v3.userrank')),
            ],
            options={
                'db_table': 'my-rank_scores',
            },
        ),
    ]
