# Generated by Django 5.0.6 on 2024-10-26 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0021_rankscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rank_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rank_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
