# Generated by Django 5.0.6 on 2024-10-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0022_usermodel_rank_time_usermodel_rank_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='v3.usermodel')),
            ],
            options={
                'db_table': 'my-rank_history',
            },
        ),
    ]
