# Generated by Django 5.0.6 on 2024-10-26 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0023_rankhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
