# Generated by Django 5.0.6 on 2024-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0024_alter_rankhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='rankhistory',
            name='rank_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankhistory',
            name='user',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
