# Generated by Django 5.0.6 on 2024-10-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0025_remove_rankhistory_id_alter_rankhistory_rank_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rankhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='v3.usermodel'),
        ),
    ]
