# Generated by Django 5.0.6 on 2024-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0026_rankhistory_id_alter_rankhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
