# Generated by Django 5.0.6 on 2024-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0027_alter_rankhistory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankhistory',
            name='rank_value',
        ),
        migrations.RemoveField(
            model_name='rankhistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='rankhistory',
            name='user',
        ),
        migrations.AlterModelTable(
            name='rankhistory',
            table=None,
        ),
    ]
