# Generated by Django 5.0.6 on 2024-10-27 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0028_remove_rankhistory_rank_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='rank_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rankhistory',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='v3.usermodel'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='rankhistory',
            table='my-rank_history',
        ),
    ]
