# Generated by Django 5.0.6 on 2024-10-27 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0029_rankhistory_rank_value_rankhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
