# Generated by Django 5.0.6 on 2024-10-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0030_userrank_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='posture',
            field=models.CharField(default='', max_length=100),
        ),
    ]
